openapi: 3.0.0
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
paths:
  /signin:
    post:
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                Email:
                  type: string
                password:
                  type: string
                token:
                  type: string
              required:
                - Email
                - password
                - token
      responses:
        '200':
          description: Success Request
      tags:
        - signin
      operationId: Signin
      summary: Signin
